/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SYNCH_PRIVATE_H
#define SYNCH_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"4.2.7.0"
#define VER_MAJOR	4
#define VER_MINOR	2
#define VER_RELEASE	7
#define VER_BUILD	0
#define COMPANY_NAME	"CBL"
#define FILE_VERSION	"4.27"
#define FILE_DESCRIPTION	"synch"
#define INTERNAL_NAME	"synch.exe"
#define LEGAL_COPYRIGHT	"CBL@2009"
#define LEGAL_TRADEMARKS	"CBL@2009"
#define ORIGINAL_FILENAME	"synch.exe"
#define PRODUCT_NAME	"synch.exe"
#define PRODUCT_VERSION	"4.27"

#endif /*SYNCH_PRIVATE_H*/
