// Class automatically generated by Dev-C++ New Class wizard

#ifndef ARBO_H
#define ARBO_H

#include <io.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <stdarg.h>
#include "fichier.h"

#define MAX_ITEMS_PER_REP 1500

struct st_items
{
       int typ; //0 fichier 
                 //1 répertoire
       class c_fichier      *fichier;
       struct st_repertoire *repertoire;
};


struct st_repertoire
{
    char             name[FILENAME_MAX];
   	struct  st_items items[MAX_ITEMS_PER_REP];		
};

/*
 * No description
 */
class c_arbo
{
    private:
        //tableau de fichier
        struct  st_repertoire racine;
        long max_fich;
    
	public:
		// class constructor
		c_arbo( char *nom);
		// class destructor
		~c_arbo();
		int parcourir(char *chemin,struct st_repertoire *rep);
		void afficher(char *chemin,struct st_repertoire *rep);
		void show();
};

#endif // ARBO_H
