// Class automatically generated by Dev-C++ New Class wizard

#ifndef ARBO_H
#define ARBO_H

#include <io.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <stdarg.h>
#include "liste_chainee.h"
#define MAX_CHAINE 8192

/*
 * No description
 */
class c_arbo
{
    private:
        c_liste_chainee liste;
        char racine[MAX_CHAINE];
		int parcourir(char *chemin);
    
	public:
		// class constructor
		c_arbo( char *nom);
		// class destructor
		~c_arbo();
	    void fic_en_moins(c_arbo *DST);
		void fic_en_trop(c_arbo *SRC);
		c_liste_chainee* get_liste();

};

#endif // ARBO_H
